import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import PokemonLogo from '../public/pokemon-logo.png'
import Link from 'next/link'
import { useRouter } from 'next/router';

export default function Layout({title, children}){
    const router = useRouter();
    const activeLink = (url, pathname) => pathname === url ? "nav-link active" : "nav-link";

    const searchPokemon = () => {
        const query = document.getElementById('search').value
        router.push(`/pokemon/${query.toLowerCase()}`)
    }
    return(
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
                <div class="container">
                    <a class="navbar-brand" href="/">
                        <Image src={PokemonLogo} alt="Pokemon Logo" height={48}/>
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <Link class={`${activeLink('/', router.pathname)}`} aria-current="page" href="/">Home</Link>
                            <Link class={`${activeLink('/pokemon', router.pathname)}`} aria-current="page" href="/pokemon">Pokemon</Link>
                            <Link class={`${activeLink('/item', router.pathname)}`} aria-current="page" href="/item">Item</Link>
                        </ul>
                        <div className="row">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Enter pokemon name" id='search'/>
                                <button class="btn btn-outline-warning" type="button" id="search-btn" onClick={() => searchPokemon()}>Search</button>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
            <main className="main py-4" style={{background: "linear-gradient(rgba(0,0,0,0.35), rgba(0,0,0,0.35)), url('/pokemon-background.jpg')", backgroundSize: "cover", backgroundRepeat: "no-repeat"}}>
                {children}
            </main>
            <footer className="footer bg-dark py-4">
                <div className="container">
                    <p className="text-center text-white mb-0">© 2022 Pokémon. © 1995–2022 Nintendo/Creatures Inc./GAME FREAK inc.</p>
                </div>
            </footer>
        </>
    )
}